### ISSUE TITLE
demodata

### ISSUE THREAD

**Issue by ygrange** [tammojan/taql-jupyter#2]
I am trying to build this for a small test I am doing (I'll get back to you about that later) but I noticed that the demodata.tgz is not packed with the install. Are you planning to make it available (even if it's just as a download from your private ASTRON homedir)? 

I found it btw, so you don't need to bother making it available to me per se.

**Comment by tammojan** [comment]
It's 120 MB, so too large to put in into the repository. I added it through git-lfs in 2fe9d37
